version: '3'
services:
  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_ENCODING=UTF-8
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    restart: unless-stopped
