index:
    path: /
    controller: App\Controller\PingController::ping

finances_summary:
    path: /finances
    controller: App\Controller\FinancesController::summary

finances_incomes:
    path: /finances/incomes
    controller: App\Controller\FinancesController::incomes
